# Generated by Django 6.0.3 on 2026-05-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees_url', models.URLField(blank=True, help_text='Например: https://1c.example.com/hs/exchange/employees/', max_length=500, verbose_name='URL сотрудников (XML)')),
                ('clients_url', models.URLField(blank=True, help_text='Например: https://1c.example.com/hs/exchange/clients/', max_length=500, verbose_name='URL клиентов (XML)')),
                ('last_sync_employees', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация сотрудников')),
                ('last_sync_clients', models.DateTimeField(blank=True, null=True, verbose_name='Последняя синхронизация клиентов')),
            ],
            options={
                'verbose_name': 'Настройки синхронизации',
                'verbose_name_plural': 'Настройки синхронизации',
            },
        ),
    ]
