# Generated by Django 6.0.3 on 2026-04-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='receiver_email',
            field=models.EmailField(max_length=254, verbose_name='Получатель'),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Тема'),
        ),
    ]
